HardySimpson/zlog

src/rule.c

As title. #74 fix breaks if the config file contains "#s" or "#r" in archive path

Fix judgement since #r and #s must be exist once in archive path

---

src/fmacros.h

Buildroot always specifies -D_LARGEFILE_SOURCE, -D_LARGEFILE64_SOURCE,
-D_FILE_OFFSET_BITS=64, so define them only, if they are not already
defined.
Signed-off-by: Yegor Yefremov <yegorslists@googlemail.com>

Fix compiling on Buildroot

---

src/event.c

On 64bit machines it ends up in errors
event.c:85:67: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
a_event->tid_hex_str_len = sprintf(a_event->tid_hex_str, "0x%x", (unsigned int)a_event->tid);
Signed-off-by: Khem Raj <raj.khem@gmail.com>

event.c: Cast pthread_t to unsigned long instead of unsigned int

---

src/makefile

Using -Werror on production is a bad idea, as otherwise harmless warnings
get treated as errors breaking builds. This is currently the case with
Nios-II architecture toolchain, warning about a deprecated macro:
../usr/nios2-buildroot-linux-gnu/sysroot/usr/include/features.h:148:3:
error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
Instead of trying to fix the macro, let's fix the real issue here,
and remove -Werror.
Signed-off-by: Ezequiel Garcia ezequiel@vanguardiasur.com.ar

compile: Remove -Werror and avoid build failures because of warnings

---

test/makefile
test/test_leak.c
test/test_multithread.c
test/test_multithread.conf
test/test_press_write.c
test/test_press_write2.c

I wrote the test/test_multithread program to check the "Multithread issue locks until log file rotation #93" issue. I don't confirm this issue. This program start threads  and reload periodicaly the configuration. The main loop is also able to detect a configuration file update and will reload the new configuration. To stop the test, simply hit Ctrl-C and chech statistics on screen.
The second commit solve some warnings on compilation

Add a multi-threads test and suppress some compilation warnings

---

src/rule.c
test/makefile
test/test_category.c
test/test_category.conf

Category names can contain '-' character also. New Tests to
check correct category names are accepted.
Signed-off-by: Henrique Marks <henrique.marks@datacom.ind.br>

Add '-' to the list of accepted characters in category name

---

doc/UsersGuide-EN.lyx
src/buf.c
src/buf.h
src/event.c
src/event.h
src/makefile
src/spec.c
src/spec.h
src/zlog.c
src/zlog.h
test/test_buf.c
test/test_multithread.c
test/test_multithread.conf

Ability to use %k for getting thread id.
Formatting with 0 fill.
Centos 7 build fixes.
Extra public zlog_level_enabled call for a category to test if a log level would result in an actual log. This is so the user can check this before doing lots of work putting a log entry together.

Add thread id formatter, leading 0's formatting, log level checking and build fixes

---

src/buf.c
src/category.c
src/event.c
src/format.c
src/level.c
src/mdc.c
src/record.c
src/rotater.c
src/rule.c
src/spec.c
src/thread.c
src/zc_arraylist.c

Fixed memory bug where deallocated memory was being accessed after it was released back to the system.

Bug fix for memory blocks being accessed after being freed.

---

src/zlog.c
src/zlog.h
test/makefile
test/test_enabled.c
test/test_enabled.conf
test/test_enabled.h

This commit adds an API to check if a given level is enabled before
build the message. Macros for default levels is also provided.
Sometimes the effort to build a complex/detailed log message can be very
costly, so it is useful in some applications to check if some level is
enabled in a category before take the decision to build the message.
Signed-off-by: Filipe Utzig <filipe.utzig@datacom.ind.br>

Added API to see if a given level is enabled

---

src/rule.c

a_rule->static_fd may be set to -1, https://github.com/HardySimpson/zlog/blob/ac1a4782b80bce7adb2d9197bd332a334eb2b530/src/rule.c#L829.

fix zlog_rule_del close invalid fd

---

src/spec.c

This feature is needed if one would like to have a command prompt which updates itself. 
Like a clock. One could add the '\r' character directly into the config file but this is more like an ugly hack.

added support for %r to insert a carriage return

---

README.md
src/level_list.h
src/rule.h
src/zlog.c

There is a small typo in README.md, src/level_list.h, src/rule.h, src/zlog.c.
Should read `output` rather than `ouput`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, ouput -> output

---

src/conf.c

Simple fix to get rid of the valgrind error 'Conditional jump or move depends on uninitialised value'.

Fix valgrind error

---

src/conf.c

A check was missing on the config variable, and this could lead
to a segfault, when zlog was initialized without a config file.
Signed-off-by: polnico <pol.nicolai@gmail.com>

Bugfix: possible segfault in config

---

src/fmacros.h

Signed-off-by: Zhentao Huang <zhentao_huang@hotmail.com>
For [auto tool](https://github.com/bmanojlovic/zlog) fork
* OS : MacOSX 12.6.1
* SDK : MacOSX 13.0
* autoconf : 2.71
* automake : 1.16.5
* compiler : apple clang 14.0.0
zlog is not able to pass compiling on MacOSX with SDK 13.0( either with 11.3 or 12.3)
```
../../src/event.c:97:5: error: implicit declaration of function 'pthread_threadid_np' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
pthread_threadid_np(NULL, &tid64);
```
1. In MacOSX sdks `pthread/phtread.h` wrapped declaration of `pthread_thread_np` with a condition like this:
```
#if (!defined(_POSIX_C_SOURCE) && !defined(_XOPEN_SOURCE)) || defined(_DARWIN_C_SOURCE) || defined(__cplusplus) // line 520, OSX sdk 13.0
...
int pthread_threadid_np(pthread_t …
```

Fix #226 compiling issue for auto-tool fork

---

src/lockfile.c

Each time zlog rotates the logs, lock file will be opened. However, when the lock file already exists, this O_EXCL flag will cause the open command to return an error.

Fix #237 rotate fail

---

src/rule.c

when we set rotate-file-limit to `1GB`，however, the variable `archive_max_size` will be set to values `1`, this is a bug !!!
when we write ***1B*** data use `dzlog_info()`，***data length is equal to `archive_max_size`***, this may cause log file rotated, even though current log file size is much less than  rotate limit;
The configuration file is as follows:
```ini
[formats]
simple = "%m%n"
[rules]
*.*  "./test.log", 1GB * 0 ~ "./test.log.#s"; simple
```

bug for rotating log file when archive_max_size is GB

---

src/spec.c

can`t parse the documented spec ```%g(%F)``` which has params in ()
https://github.com/HardySimpson/zlog/commit/26263f96eb78e016e9b0b75797f9ec315c2e1897#r138249594

Fix %g spec cause zlog conf parse failed

---

src/rule.c

Size of `record_name` is **`MAXLEN_PATH(1024) + 1`** but `file_path` may have data upto **`MAXLEN_CFG_LINE(MAXLEN_PATH*4) + 1`**. So a check was missing in `zlog_rule_new()` while copying the `record_name` from `file_path + 1` which caused the buffer overflow. An attacker can exploit this vulnerability to overwrite the `zlog_record_fn record_func` function pointer to get arbitrary code execution.

CVE-2024-22857: buffer overflow patched

---

src/zlog.c

Log printing interfaces, such as `zlog` and `vzlog`, do not invoke `zlog_env_lock` to lock when accessing `zlog_env_conf`.
However, the `zlog_reload` interface deletes `zlog_env_conf` from the lock. As a result, a null pointer error occurs.

 Fix zlog_env_conf concurrency question

---

src/conf.c

#159 引入 log_level 默认值，但是在未配置的情况下，默认值是`\0`，引发 `ERROR (1891873:level_list.c:141) str is [], can't find level` 错误。

fix "str is [], can't find level" error

---

src/zlog.c

WIP: fix #276: double-free panic in gcc attribute destructor logging

---

src/zlog.c
src/zlog.h

It would be great to have a simple way to determine if a certain log level is enabled for the default (dzlog) api!

Add dzlog_level_enabled()

---

src/event.c

Both `buf.c` and `event.c` use the `uint64_t` type. However, only `buf.c` includes `<stdint.h>` to use this integer type, and that situation breaks some old (but compatible) compilers:
```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_zlog/zlog/work/zlog-1.2.18/src/event.c:106:13: error: expected ';' after expression
uint64_t tid64;
^
;
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_zlog/zlog/work/zlog-1.2.18/src/event.c:106/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_zlog/zlog/work/zlog-1.2.18/src/event.c:106::13: error: expected ';' after expression5
uint64_t tid64;
^
;
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_zlog/zlog/work/zlog-1.2.18/ …
```

event.c: include stdint header
